# Generated by Django 4.2.5 on 2023-09-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_dog_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dog', verbose_name='собака')),
            ],
            options={
                'verbose_name': 'ошейник',
                'verbose_name_plural': 'ошейники',
            },
        ),
    ]
