# Generated by Django 4.2.5 on 2023-09-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_collar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collar',
            new_name='Food',
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'корм', 'verbose_name_plural': 'корма'},
        ),
    ]
