# Generated by Django 4.2.5 on 2023-09-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_collar_food_alter_food_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='почта'),
        ),
    ]
