# Generated by Django 4.2.5 on 2023-09-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_dog_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='кличка')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.breed', verbose_name='порода')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dog', verbose_name='собака')),
            ],
        ),
    ]
